### PR TITLE
Add improvements for some sections, docs, faqs, terms, and privacy policy

### PR DESCRIPTION
**Pull request by mariano-aguero**
The docs and faqs section have the same look and feel.
The terms and conditions and privacy policy section have the same look and feel.
All four sections use the same fonts.

### CODE REVIEW

**Comment by mariano-aguero** [comment]
Terms section
terms

**Comment by mariano-aguero** [comment]
Privacy section
privacy

**Comment by mariano-aguero** [comment]
Part of the docs section, there are some tag em that I don't like, but they were already like this

docs

**Comment by mariano-aguero** [comment]
Faqs section, we are working in the sidedrawer in another PR...

faqs

**Comment by mariano-aguero** [comment]
Regarding the DOCS section and the FAQ, both have the same styles, same separation in the lists, same types of titles, in both there is a lot of use of the strong and em tag, which I don't like, but others may like it so I left them like that. This kind of tags generates an effect of "distortion" if someone look at both sections, and gives the feeling that they were different, but it is not like that.

**Review by galimba — APPROVED** [review]
LGTM

**Review by pmprete — APPROVED** [review]
Good work, agree im not a fan of em and string as well

**Pull request merged**
